// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntrevistaSoloTalentoBackend.Models
{
    public partial class Clients
    {
        public Clients()
        {
            Sales = new HashSet<Sales>();
        }

        public int IDClient { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Direction { get; set; }
        public int? UserID { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}