// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EntrevistaSoloTalentoBackend.Models
{
    public partial class EntrevistaSoloTalentoContext : DbContext
    {
        public EntrevistaSoloTalentoContext()
        {
        }

        public EntrevistaSoloTalentoContext(DbContextOptions<EntrevistaSoloTalentoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<StoreProducts> StoreProducts { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-86FDGJM\\MSSQLSERVER01;Initial Catalog=EntrevistaSoloTalento;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Clients>(entity =>
            {
                entity.HasKey(e => e.IDClient)
                    .HasName("PK__Clients__CDECAB2C2FABCA6D");

                entity.Property(e => e.IDClient).ValueGeneratedNever();

                entity.Property(e => e.Direction)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.LastName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Clients)
                    .HasForeignKey(d => d.UserID)
                    .HasConstraintName("FK__Clients__UserID__398D8EEE");
            });

            modelBuilder.Entity<Products>(entity =>
            {
                entity.HasKey(e => e.Code)
                    .HasName("PK__Products__A25C5AA685E575A6");

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.Description)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Image)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            });

            modelBuilder.Entity<Sales>(entity =>
            {
                entity.HasKey(e => e.SaleID)
                    .HasName("PK__Sales__1EE3C41FA39ACEAD");

                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.ClientNavigation)
                    .WithMany(p => p.Sales)
                    .HasForeignKey(d => d.Client)
                    .HasConstraintName("FK__Sales__Client__4222D4EF");

                entity.HasOne(d => d.ProductNavigation)
                    .WithMany(p => p.Sales)
                    .HasForeignKey(d => d.Product)
                    .HasConstraintName("FK__Sales__Product__4316F928");
            });

            modelBuilder.Entity<Store>(entity =>
            {
                entity.HasKey(e => e.IDStore)
                    .HasName("PK__Store__BD8985FA4D3B9C0B");

                entity.Property(e => e.IDStore).ValueGeneratedNever();

                entity.Property(e => e.Direction)
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<StoreProducts>(entity =>
            {
                entity.HasKey(e => e.StoreProductID)
                    .HasName("PK__StorePro__629CD728475F9BC1");

                entity.Property(e => e.RegistrationDate).HasColumnType("date");

                entity.HasOne(d => d.ProductNavigation)
                    .WithMany(p => p.StoreProducts)
                    .HasForeignKey(d => d.Product)
                    .HasConstraintName("FK__StoreProd__Produ__3F466844");

                entity.HasOne(d => d.StoreNavigation)
                    .WithMany(p => p.StoreProducts)
                    .HasForeignKey(d => d.Store)
                    .HasConstraintName("FK__StoreProd__Store__403A8C7D");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.HasKey(e => e.UserID)
                    .HasName("PK__Users__1788CCACB439434F");

                entity.Property(e => e.UserID).ValueGeneratedNever();

                entity.Property(e => e.Password)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Username)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}