// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntrevistaSoloTalentoBackend.Models
{
    public partial class Sales
    {
        public int? Client { get; set; }
        public int? Product { get; set; }
        public DateTime? Date { get; set; }
        public int SaleID { get; set; }
        public bool? Bought { get; set; }

        public virtual Clients ClientNavigation { get; set; }
        public virtual Products ProductNavigation { get; set; }
    }
}