// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntrevistaSoloTalentoBackend.Models
{
    public partial class StoreProducts
    {
        public int? Product { get; set; }
        public int? Store { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public int StoreProductID { get; set; }

        public virtual Products ProductNavigation { get; set; }
        public virtual Store StoreNavigation { get; set; }
    }
}