// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntrevistaSoloTalentoBackend.Models
{
    public partial class Store
    {
        public Store()
        {
            StoreProducts = new HashSet<StoreProducts>();
        }

        public int IDStore { get; set; }
        public string Direction { get; set; }
        public string Branch { get; set; }

        public virtual ICollection<StoreProducts> StoreProducts { get; set; }
    }
}