// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntrevistaSoloTalentoBackend.Models
{
    public partial class Users
    {
        public Users()
        {
            Clients = new HashSet<Clients>();
        }

        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool? IsManager { get; set; }

        public virtual ICollection<Clients> Clients { get; set; }
    }
}